# Generated by Django 5.1.4 on 2025-01-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_estoque', models.IntegerField()),
                ('valor_estoque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField()),
                ('data_validade', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
