# Generated by Django 5.1.5 on 2025-03-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
