# Generated by Django 5.1.4 on 2025-01-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtd_estoque',
            new_name='qtd_estoque_inicial',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_venda',
        ),
    ]
