# Generated by Django 5.1.5 on 2025-03-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_delete_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
