# Generated by Django 5.1.5 on 2025-03-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_preco_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retirada',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Retirada',
        ),
    ]
