# Generated by Django 5.1.4 on 2025-01-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirada',
            name='data_retirada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
