# Generated by Django 5.1.5 on 2025-01-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tipo',
            field=models.CharField(default='entrada', max_length=255),
        ),
        migrations.AddField(
            model_name='retirada',
            name='tipo',
            field=models.CharField(default='retirada', max_length=255),
        ),
    ]
